from tkinter import*
from PIL import Image , ImageTk
import speech_to_text
import action
root = Tk()
root.title("AI Assistent")
root.geometry("550x675")
root.resizable(False , False)
root.config(bg="#6F8FAF")

# ask fun
def ask ():
    user_val =speech_to_text.speech_to_text()
    bot_val = action.Action(user_val)
    text.insert(END , 'User--->'+ user_val+"\n")
    if bot_val !=None:
        text.insert(END , 'OUT <---'+ str(bot_val) +"\n")
    if bot_val == "ok sir":
        root.destroy()



def Send ():
    send = entry.get()
    bot = action.Action(send)
    text.insert(END , 'User---->'+ send+"\n")
    if bot !=None:
        text.insert(END , 'BOT <----'+ str(bot) +"\n")
    if bot == "ok sir":
        root.destroy()


def del_text ():
   text.delete("1.0","end")

#frame

frame = LabelFrame(root , padx=100 , pady=7 , borderwidth=3 , relief="raised")
frame.config(bg="#6F8FAF")
frame.grid(row = 0 , column = 1, padx = 90 , pady= 10)

#text lable

text_label= Label(frame, text="AI Assistent" , font=("comic sans ms" , 14 , " bold") )
text_label.grid(row = 0 , column = 0, padx = 20 , pady= 10)

#image

#image = ImageTk.PhotoImage(Image.open("image/dilkhush.jpg"))
#image_label= Label(frame , image=image)
#image_label.grid(row =0, column = 0 , pady = 0)

# adding a text widget

text = Text(root, font=('courier 10 bold'), bg ="#356696")
text.grid(row=2 , column=0)
text.place(x= 100 , y= 200, width=350 , height=250 )

# entry widget
entry = Entry(root , justify=CENTER)
entry.place(x=100 , y = 500 , width= 350 , height= 60)

# bitton1
Button1 =Button(root , text = "Ask" , bg="#356696" , pady=16, padx=40, borderwidth=3 ,relief=SOLID, command= ask) 
Button1.place(x=70 , y = 575 )

# bitton2
Button2 =Button(root , text = "Send" , bg="#356696" , pady=16, padx=40, borderwidth=3 ,relief=SOLID, command= Send) 
Button2.place(x=400 , y = 575 )


# bitton3
Button3 =Button(root , text = "Delete" , bg="#356696" , pady=16, padx=40, borderwidth=3 ,relief=SOLID, command= del_text) 
Button3.place(x=225 , y = 575 )


root.mainloop()